touch app.js
mkdir docker
touch docker/build-Run-azure.sh
touch docker/docker-compose-azure.yaml
touch docker/docker-compose-local.yaml
touch docker/docker-compose-qa.yaml
touch docker/docker-compose-server.yaml
touch Dockerfile
mkdir lib
touch lib/generateToken.js
touch lib/hasher.js
touch lib/responseErrorHandler.js
touch lib/sendResponse.js
touch lib/sha3Hashing.js
touch lib/util.js
touch lib/validationError.js
mkdir loaders
mkdir loaders/defaultCountry
mkdir loaders/defaultStates
touch loaders/defaultCountry/defaultCountryData.js
touch loaders/defaultCountry/defaultCountry.js
touch loaders/defaultStates/defaultStateData.js
touch loaders/defaultStates/defaultState.js
touch loaders/dotenv.js
touch loaders/emailConfig.js
touch loaders/express.js
touch loaders/handleError.js
touch loaders/jwt.js
touch loaders/logger.js
touch loaders/mongoose.js
touch loaders/whatsapp.js
mkdir logs
touch logs/applog
mkdir models
touch models/usersModel.js
mkdir node_modules
touch package.json
touch README.md
mkdir routes
touch routes/index.js
mkdir services
