version: "3.8"
services:
  mymongo:
    image: mongo:5.0.2
    ports:
      - "27017:27017"
    hostname: mymongo
    volumes:
      - /home/akshith/mongo_backup/:/db
      

  myprojectapi:
    image: myprojectapi
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    hostname: myprojectapi
    environment:
      - EXPRESS_PORT=3000
      - EXPRESS_HOST=0.0.0.0
      - MONGO_URI=mongodb+srv://akshithsistla:ccipnWsoxp5NQ0nm@cluster0.iljkeyx.mongodb.net/projectdatabase

    volumes:
      - /home/akshith/desktop/my project
      - /home/akshith/desktop/my project/node_modules
    depends_on:
      - mymongo
    ports:
      - "3001:3001"
    command: nodemon --legacy-watch server.js
