version: '3.8'

services:
  app:
    image: myprojectapi:latest
    ports:
      - "3000:3000"
    depends_on:
      - mongo
    volumes:
      - .:/app
    environment:
      - MONGO_URI=mongodb://mongo:27017/bookingDB
    command: nodemon app.js

  mongo:
    image: mongo:4.4
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
